[package]
authors = ["Twilight Contributors"]
categories = ["caching"]
description = "In-process-memory based cache for the Twilight ecosystem."
documentation = "https://docs.rs/twilight-cache-inmemory"
edition = "2021"
homepage = "https://twilight.rs/chapter_1_crates/section_4_cache_inmemory.html"
include = ["src/**/*.rs", "README.md"]
keywords = ["discord", "discord-api", "twilight"]
license = "ISC"
name = "twilight-cache-inmemory"
publish = true
repository = "https://github.com/twilight-rs/twilight"
readme = "README.md"
rust-version = "1.60"
version = "0.12.0"

[dependencies]
bitflags = { default-features = false, version = "1" }
dashmap = { default-features = false, version = "5.3" }
serde = { default-features = false, features = ["derive"], version = "1" }
twilight-model = { default-features = false, path = "../twilight-model", version = "0.12.1" }

# Optional dependencies.
twilight-util = { default-features = false, features = ["permission-calculator"], optional = true, path = "../twilight-util", version = "0.12.0" }

[dev-dependencies]
futures = { default-features = false, version = "0.3" }
static_assertions = { default-features = false, version = "1" }
tokio = { default-features = false, features = ["macros", "rt-multi-thread"], version = "1.0" }
twilight-gateway = { default-features = false, features = ["rustls-native-roots"], path = "../twilight-gateway" }

[features]
permission-calculator = ["dep:twilight-util"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
